# Generated by Django 3.2.3 on 2021-07-16 14:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('content_en', models.TextField(null=True, verbose_name='content')),
                ('content_uz', models.TextField(null=True, verbose_name='content')),
                ('content_ru', models.TextField(null=True, verbose_name='content')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='ChefModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='image')),
                ('job', models.CharField(max_length=255, verbose_name='job')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description')),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'chef',
                'verbose_name_plural': 'chefs',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('message', models.TextField(null=True, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
            },
        ),
    ]
