# Generated by Django 3.2.3 on 2021-07-16 15:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutPageModel',
            new_name='AboutModel',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
    ]
