# Generated by Django 3.2.3 on 2021-07-17 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'food category',
                'verbose_name_plural': 'food categories',
            },
        ),
        migrations.CreateModel(
            name='FoodTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='name')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'food tag',
                'verbose_name_plural': 'food tags',
            },
        ),
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='price')),
                ('food_name', models.CharField(max_length=25, verbose_name='food name')),
                ('food_name_en', models.CharField(max_length=25, null=True, verbose_name='food name')),
                ('food_name_uz', models.CharField(max_length=25, null=True, verbose_name='food name')),
                ('food_name_ru', models.CharField(max_length=25, null=True, verbose_name='food name')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('category', models.ManyToManyField(related_name='pages', to='foods.FoodCategoryModel')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='foods.foodtagmodel')),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'foods',
            },
        ),
    ]
