# Generated by Django 3.2.3 on 2021-07-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_foodcategorymodel_foodmodel_foodtagmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': 'About'},
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='tags',
            field=models.ManyToManyField(related_name='pages', to='foods.FoodTagModel'),
        ),
    ]
