# Generated by Django 3.2.3 on 2021-07-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20210718_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='tags',
            field=models.ManyToManyField(related_name='image', to='foods.FoodTagModel'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
