# Generated by Django 3.2.3 on 2021-07-20 06:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_auto_20210718_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFoodsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='title')),
                ('title_en', models.CharField(max_length=25, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=25, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=25, null=True, verbose_name='title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('price', models.FloatField(verbose_name='price')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'shop food',
                'verbose_name_plural': 'shop foods',
            },
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
    ]
