# Generated by Django 3.2.3 on 2021-07-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordermodel_food'),
        ('foods', '0007_auto_20210720_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodModel',
            new_name='HomeFoodModel',
        ),
        migrations.AlterModelOptions(
            name='homefoodmodel',
            options={'verbose_name': 'home food', 'verbose_name_plural': 'home foods'},
        ),
    ]
