# Generated by Django 3.2.3 on 2021-07-20 06:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_auto_20210720_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopfoodsmodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopfoodsmodel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='shopfoodsmodel',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='shopfoodsmodel',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='shopfoodsmodel',
            name='content',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='shopfoodsmodel',
            name='content_en',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='shopfoodsmodel',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='shopfoodsmodel',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='content'),
        ),
    ]
