# Generated by Django 3.2.3 on 2021-07-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_auto_20210720_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopfoodsmodel',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='foods.FoodCategoryModel'),
        ),
        migrations.AlterField(
            model_name='homefoodmodel',
            name='category',
            field=models.ManyToManyField(related_name='category', to='foods.FoodCategoryModel'),
        ),
    ]
