# Generated by Django 3.2.3 on 2021-07-26 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_auto_20210725_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopfoodsmodel',
            name='category',
        ),
    ]
