# Generated by Django 3.2.3 on 2021-07-26 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_remove_shopfoodsmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopfoodsmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='foods.foodcategorymodel'),
        ),
    ]
