# Generated by Django 3.2.3 on 2021-07-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0014_alter_shopfoodsmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopfoodsmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='shopfoodsmodel',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='foods', to='foods.FoodCategoryModel'),
        ),
    ]
