# Generated by Django 3.2.3 on 2021-07-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0015_auto_20210726_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopfoodsmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='shopfoodsmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='foods.foodcategorymodel'),
        ),
    ]
