# Generated by Django 3.2.3 on 2021-08-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0016_auto_20210730_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('message', models.TextField(null=True, verbose_name='message')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments2', to='foods.shopfoodsmodel')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
            },
        ),
    ]
