# Generated by Django 3.2.3 on 2021-08-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0017_comment2model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChefModel',
        ),
    ]
