# Generated by Django 3.2.3 on 2021-08-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0020_auto_20210816_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='image',
        ),
    ]
