# Generated by Django 3.2.3 on 2021-08-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0017_comment2model'),
        ('bot_users', '0002_telegramusermodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusermodel',
            name='tg_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ManyToManyField(related_name='orders', to='foods.ShopFoodsModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bot_users.telegramusermodel')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
