# Generated by Django 3.2.3 on 2021-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210717_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
    ]
