# Generated by Django 3.2.3 on 2021-07-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210721_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='blog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.blogmodel'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.ManyToManyField(related_name='category', to='post.CategoryModel'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tag', to='post.BlogTagModel'),
        ),
    ]
