# Generated by Django 3.2.3 on 2021-07-16 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55, verbose_name='first name')),
                ('last_name', models.CharField(max_length=55, verbose_name='last name')),
                ('company', models.CharField(max_length=55, verbose_name='company')),
                ('phone', models.IntegerField(null=True, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('address1', models.CharField(max_length=55, verbose_name='address1')),
                ('address2', models.CharField(max_length=55, verbose_name='address2')),
                ('city', models.CharField(max_length=55, verbose_name='city')),
                ('state', models.CharField(max_length=55, verbose_name='state')),
                ('postcode', models.CharField(max_length=55, verbose_name='postcode')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('food', models.ManyToManyField(related_name='order', to='pages.FoodModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
