# Generated by Django 3.2.3 on 2021-07-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_foodcategorymodel_foodmodel_foodtagmodel'),
        ('order', '0002_remove_ordermodel_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='food',
            field=models.ManyToManyField(related_name='order', to='foods.FoodModel'),
        ),
    ]
